rails_app/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :txns
  root to: 'pages#home'
  resources :banks
  resources :users
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails_app/app/models/txn.rb
class Txn < ApplicationRecord
  include AASM

  belongs_to :txn_status
  belongs_to :txn_type
  belongs_to :user
  belongs_to :src_bank, class_name: 'Bank'
  belongs_to :dst_bank, class_name: 'Bank'

  after_create :process!

  aasm requires_lock: true do
    # Processing
    state :created, initial: true
    state :processing
    state :success
    state :rejected

    event :process do
      transitions from: :created, to: :processing
    end

    event :check do
      transitions from: :processing, to: :rejected, guard: :below_treshold?
      transitions from: :processing, to: :success
    end
  end

  private def below_treshold?
    amt.to_f < 100.0
  end
end

rails_app/app/controllers/txns_controller.rb
class TxnsController < ApplicationController
  before_action :set_txn, only: [:show ]

  # GET /txns
  # GET /txns.json
  def index
    @txns = Txn.all
  end

  # GET /txns/1
  # GET /txns/1.json
  def show
  end

  # GET /txns/new
  def new
    @txn = Txn.new
    @txn_type_list = TxnType.all
    @bank_list = Bank.all
  end

  # GET /txns/1/edit
  def edit
  end

  # POST /txns
  # POST /txns.json
  def create
    unless ENV["IS_SIDEKIQ"]
      @txn = Txn.new(txn_params)
      @txn.txn_status_id = 1
      @txn.user_id = 1
    end

    respond_to do |format|
      ## Need to check for validity
      if ENV["IS_SIDEKIQ"]
        @txn = Txn.create!(txn_params)
        EventFiringJob.perform_async(@txn.id, "check")
      else
        if @txn.save
          DeliveryBoy.deliver(@txn.to_json, topic: 'txn.created')
          # DeliveryBoy.deliver_async(@txn.to_json, topic: 'txn.created')
          # DeliveryBoy.produce(@txn.to_json, topic: 'txn.created')
          # DeliveryBoy.deliver_messages
        end
      end

      format.html { redirect_to @txn, notice: 'Txn was successfully created.' }
      format.json { render :show, status: :created, location: @txn }
    end
  end

  # PATCH/PUT /txns/1
  # PATCH/PUT /txns/1.json
  def update
    respond_to do |format|
      if @txn.update(txn_params)
        format.html { redirect_to @txn, notice: 'Txn was successfully created.' }
        format.json { render :show, status: :created, location: @txn }
      else
        @txn_type_list = TxnType.all
        @bank_list = Bank.all
        format.html { render :new }
        format.json { render json: @txn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /txns/1
  # PATCH/PUT /txns/1.json
  # def update
  #   respond_to do |format|
  #     if @txn.update(txn_params)
  #       format.html { redirect_to @txn, notice: 'Txn was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @txn }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @txn.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /txns/1
  # DELETE /txns/1.json
  def destroy
    @txn.destroy
    respond_to do |format|
      format.html { redirect_to txns_url, notice: 'Txn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_txn
      @txn = Txn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def txn_params
      params.require(:txn).permit(:amt, :txn_status_id, :txn_type_id, :user_id, :src_bank_id, :dst_bank_id)
    end
end

rails_app/app/helpers/txns_helper.rb
module TxnsHelper
end

rails_app/app/views/txns/_form.html.erb
<%= form_with(model: txn, local: true) do |form| %>
  <% if txn.errors.any? %>
    <div class="bg-danger">
      <h2><%= pluralize(txn.errors.count, "error") %> prohibited this txn from being saved:</h2>

      <ul>
        <% txn.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :txn_type_id %>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">
          <i class="fas fa-txn"></i>
        </span>
      </div>
      <% txn_type_options = options_from_collection_for_select(@txn_type_list, 'id', 'name') %>
      <%= form.select :txn_type_id, txn_type_options, {}, {class: "form-control"} %>
    </div>
  </div>
  <% bank_options = options_from_collection_for_select(@bank_list, 'id', 'name') %>
  <div class="form-group">
    <%= form.label :src_bank_id %>
    <%= form.select :src_bank_id, bank_options, {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= form.label :dst_bank_id %>
    <%= form.select :dst_bank_id, bank_options, {}, {class: "form-control"} %> 
  </div>
  <div class="form-group">
    <%= form.label :amt %>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">
          <i class="fas fa-wallet"></i>
        </span>
      </div>
      <%= form.text_field :amt, class: "form-control", placeholder: "Enter Amount of Txn" %>
    </div>
  </div>
  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
<% end %>
<!-- /card -->

rails_app/app/views/txns/edit.html.erb
<h1>Editing Txn</h1>

<%= render 'form', txn: @txn %>

<%= link_to 'Show', @txn %> |
<%= link_to 'Back', txns_path %>

rails_app/app/views/txns/index.html.erb
<div class="card">
  <div class="card-header border-0">
    <h3 class="card-title">Transactions (immutable)</h3>
    <div class="card-tools">
      <%= link_to '<i class="fas fa-plus-circle"></i>'.html_safe, new_txn_path, class: "btn btn-tool btn-sm" %>
    </div>
  </div>
  <div class="card-body table-responsive p-0">
    <table class="table table-striped table-valign-middle">
      <thead>
      <tr>
        <th>Txn ID</th>
        <th>Txn status</th>
        <th>Txn type</th>
        <th>User</th>
        <th>Src Bank</th>
        <th>Dst Bank</th>
        <th>Amt</th>
        <th>AASM</th>
      </tr>
      </thead>
      <tbody>
      <% if defined?(notice) %>
        <tr>
          <td colspan="9"><%= notice %></td>
        </tr>
      <% end %>
      <% @txns.each do |txn| %>
        <tr>
          <td>
            <%= link_to txn do %>
              <img src="<%= asset_path 'default-150x150.png' %>" alt="ID" class="img-circle img-size-32 mr-2">
              <%= txn.id %>
            <% end %>
          </td>
          <td><%= txn.txn_status.name %></td>
          <td><%= txn.txn_type.name %></td>
          <td><%= txn.user.name %></td>
          <td><%= txn.src_bank.name %></td>
          <td><%= txn.dst_bank.name %></td>
          <td><%= txn.amt %></td>
          <td><%= txn.aasm_state %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<!-- /.card -->

rails_app/app/views/txns/new.html.erb
<div class="card">
  <div class="card-header border-0">
    <h3 class="card-title">New Txn</h3>
    <div class="card-tools">
      <%= link_to '<i class="fas fa-plus-circle"></i>'.html_safe, new_txn_path, class: "btn btn-tool btn-sm" %>
    </div>
  </div>
  <div class="card-body table-responsive ">
    <%= render 'form', txn: @txn %>
  </div>
</div>
<!-- /.card -->

rails_app/app/views/txns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Txn status:</strong>
  <%= @txn.txn_status_id %>
</p>

<p>
  <strong>Txn type:</strong>
  <%= @txn.txn_type_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @txn.user_id %>
</p>

<p>
  <strong>Src bank:</strong>
  <%= @txn.src_bank_id %>
</p>

<p>
  <strong>Dst bank:</strong>
  <%= @txn.dst_bank_id %>
</p>

<p>
  <strong>Amt:</strong>
  <%= @txn.amt %>
</p>

<%= link_to 'Edit', edit_txn_path(@txn) %> |
<%= link_to 'Back', txns_path %>